import type {
  CoachPersona,
  DailyBrief,
  LongTermPlan,
  PlanSnapshot,
  PlanAdjustmentProposal,
  PlanSetupInput,
  SessionReport,
  UserProfile,
  WorkoutTemplate,
} from "@/lib/types";
import { regenerateLinearPlan } from "@/lib/plan-generator";
import { applyCurrentTemplateLayout } from "@/lib/template-layout";
import { isoToday, uid } from "@/lib/utils";

export const defaultPersona: CoachPersona = {
  id: "persona-primary",
  name: "FitCoach",
  voice: "冷静、直接、偏执行导向",
  mission: "把长期目标拆成每天能执行的训练和饮食处方，减少幻觉和计划漂移。",
  corePrinciples: [
    "长期目标优先于临时情绪。",
    "正式计划只在你确认后更新。",
    "训练建议必须结合最近执行情况和恢复状态。",
  ],
};

export const defaultProfile: UserProfile = {
  id: "profile-primary",
  name: "zjy",
  currentWeightKg: 60,
  targetWeightKg: 65,
  primaryGoal: "Lean Bulk 到 65kg，优先保证动作标准和稳定推进。",
  dietaryPreferences: ["食堂场景", "高碳训练日", "简单可重复"],
  restrictions: ["严格禁酒"],
  wakeWindow: "07:30 - 08:30",
  sleepTargetHours: 7.5,
  oneRepMaxes: {
    bench_press: 32,
    squat: 50,
    deadlift: 40,
    hack_squat: 80,
    rdl: 60,
    lat_pulldown: 30,
  },
  updatedAt: isoToday(),
};

export const defaultPlan: LongTermPlan = {
  id: "plan-primary",
  goal: "60kg -> 65kg Lean Bulk",
  phase: "lean_bulk",
  startDate: isoToday(),
  durationWeeks: 8,
  startingIntensityPct: 70,
  schedulePattern: "3on1off",
  baseCalendarEntries: [],
  calendarEntries: [],
  planRevisionId: "planrev-seed",
  splitType: "PPL",
  progressionRule: {
    type: "linear",
    daySequence: ["A", "B", "C"],
    weeklyPhases: [
      { week: 1, label: "初期", intensity: 0.7, repStyle: "5x10", notes: "容量基准" },
      { week: 2, label: "初期", intensity: 0.725, repStyle: "4x10", notes: "动作标准优先" },
      { week: 3, label: "中期", intensity: 0.75, repStyle: "4x8", notes: "进入肥大推进" },
      { week: 4, label: "中期", intensity: 0.775, repStyle: "3x8", notes: "控制 RPE 8-8.5" },
      { week: 5, label: "减载周", intensity: 0.8, repStyle: "3x8", notes: "负重降低 20%" },
      { week: 6, label: "冲刺期", intensity: 0.825, repStyle: "5x5", notes: "主项爆发力" },
      { week: 7, label: "冲刺期", intensity: 0.875, repStyle: "3x5", notes: "高质量完成" },
      { week: 8, label: "极限期", intensity: 0.925, repStyle: "3x3", notes: "冲击新纪录前预热" },
    ],
    defaultIncrementsKg: {
      compound: 2.5,
      accessory: 2.5,
      core: 0,
    },
  },
  deloadRule: {
    consecutiveHighFatigueDays: 3,
    lowSleepThreshold: 6,
    fixedWeek: 5,
  },
  mealStrategy: {
    trainingCarbsPerKg: 4,
    restCarbsPerKg: 3,
    proteinPerKg: 1.8,
    fatsPerKg: 0.9,
    mealSplit: [20, 20, 20, 40],
    trainingExamples: ["米饭 + 瘦肉", "面包 + 香蕉", "牛奶 + 鸡蛋", "训练后快碳 + 瘦肉"],
    restExamples: ["米饭 + 鸡胸", "土豆 + 牛肉", "鸡蛋 + 牛奶", "蔬菜多吃"],
  },
  note: "训练顺序固定为 A/B/C 顺延，错过当天不跳过。",
  manualOverrides: {
    recoveryMode: "standard",
  },
};

const defaultTemplateBlueprints: WorkoutTemplate[] = [
  {
    id: "template-a",
    dayCode: "A",
    name: "Day A / Pull",
    objective: "背部宽度与厚度并进，带二头收尾。",
    warmup: [
      "祈祷式拉伸 2 组，每组 20 秒",
      "肩胛下沉 + 颈后臂屈伸激活 2 组",
      "第一项空杆/空载 2 组热身",
    ],
    exercises: [
      {
        id: "a1",
        name: "反手高位下拉",
        category: "compound",
        focus: "下背阔厚度",
        sets: 5,
        reps: "10",
        restSeconds: 120,
        cues: ["握距同肩宽", "肘向内收", "避免借力后仰"],
        baseWeightKg: 25,
        oneRepMaxKg: 30,
        oneRepMaxRef: "lat_pulldown",
        progressionModel: "percentage",
        percentageOf1RM: 1,
        incrementKg: 2.5,
        substitutions: ["高位下拉器械变握法"],
        phaseAdaptive: true,
      },
      {
        id: "a2",
        name: "对握高位下拉",
        category: "compound",
        focus: "上背阔与大圆肌",
        sets: 4,
        reps: "10",
        restSeconds: 105,
        cues: ["身体刚性", "下拉到底夹背", "全程可控"],
        baseWeightKg: 20,
        oneRepMaxKg: 27.5,
        progressionModel: "fixed",
        incrementKg: 2.5,
        substitutions: ["辅助引体向上"],
      },
      {
        id: "a3",
        name: "窄对握绳索划船",
        category: "compound",
        focus: "背部厚度",
        sets: 4,
        reps: "10-12",
        restSeconds: 90,
        cues: ["脊柱中立", "先预紧再发力", "顶峰停 1 秒"],
        baseWeightKg: 20,
        oneRepMaxKg: 30,
        progressionModel: "fixed",
        incrementKg: 2.5,
        substitutions: ["坐姿划船"],
      },
      {
        id: "a4",
        name: "开肘划船",
        category: "accessory",
        focus: "中上背细节",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        cues: ["肩胛后缩主导", "肘走外展轨迹"],
        baseWeightKg: 12.5,
        oneRepMaxKg: 20,
        progressionModel: "fixed",
        incrementKg: 2.5,
        substitutions: ["胸托划船"],
      },
      {
        id: "a5",
        name: "绳索直臂下压",
        category: "accessory",
        focus: "背阔泵感收尾",
        sets: 3,
        reps: "15-20",
        restSeconds: 60,
        cues: ["手腕固定", "肘微屈", "慢速离心"],
        baseWeightKg: 10,
        oneRepMaxKg: 15,
        progressionModel: "fixed",
        incrementKg: 2.5,
        substitutions: ["器械下拉"],
      },
      {
        id: "a6",
        name: "杠铃弯举",
        category: "accessory",
        focus: "肱二头肌",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        cues: ["肘固定", "避免后仰借力"],
        baseWeightKg: 15,
        oneRepMaxKg: 22.5,
        progressionModel: "fixed",
        incrementKg: 2.5,
        substitutions: ["EZ 杠弯举"],
      },
    ],
  },
  {
    id: "template-b",
    dayCode: "B",
    name: "Day B / Push",
    objective: "胸肩增宽主线，主项为卧推。",
    warmup: [
      "肩胛收紧 + 橡皮带外旋 2 组",
      "俯卧撑或空杆卧推 2 组热身",
      "侧平举空手激活 20 次",
    ],
    exercises: [
      {
        id: "b1",
        name: "杠铃卧推",
        category: "compound",
        focus: "胸部主项",
        sets: 5,
        reps: "10",
        restSeconds: 150,
        cues: ["肩胛收紧", "落点稳定", "脚跟稳踩地面"],
        oneRepMaxRef: "bench_press",
        progressionModel: "percentage",
        percentageOf1RM: 1,
        incrementKg: 2.5,
        substitutions: ["器械卧推"],
        phaseAdaptive: true,
      },
      {
        id: "b2",
        name: "上斜哑铃卧推",
        category: "compound",
        focus: "上胸",
        sets: 3,
        reps: "10-12",
        restSeconds: 90,
        cues: ["肩胛贴凳", "底部拉伸充分"],
        baseWeightKg: 12.5,
        oneRepMaxKg: 20,
        progressionModel: "fixed",
        incrementKg: 2.5,
        substitutions: ["史密斯上斜卧推"],
      },
      {
        id: "b3",
        name: "哑铃推举",
        category: "compound",
        focus: "肩部主项",
        sets: 4,
        reps: "10-12",
        restSeconds: 90,
        cues: ["核心收紧", "上推不过度耸肩"],
        baseWeightKg: 10,
        oneRepMaxKg: 15,
        progressionModel: "fixed",
        incrementKg: 2.5,
        substitutions: ["器械肩推"],
      },
      {
        id: "b4",
        name: "侧平举",
        category: "accessory",
        focus: "肩中束",
        sets: 4,
        reps: "15-20",
        restSeconds: 60,
        cues: ["轻重量高质量", "肘领先手腕"],
        baseWeightKg: 5,
        oneRepMaxKg: 8,
        progressionModel: "fixed",
        incrementKg: 1,
        substitutions: ["绳索侧平举"],
      },
      {
        id: "b5",
        name: "绳索下压",
        category: "accessory",
        focus: "肱三头",
        sets: 3,
        reps: "12-15",
        restSeconds: 60,
        cues: ["肘夹紧", "顶峰锁定"],
        baseWeightKg: 15,
        oneRepMaxKg: 20,
        progressionModel: "fixed",
        incrementKg: 2.5,
        substitutions: ["双杠臂屈伸"],
      },
    ],
  },
  {
    id: "template-c",
    dayCode: "C",
    name: "Day C / Legs",
    objective: "腿部主项与核心稳定一起推进。",
    warmup: [
      "髋屈伸动态拉伸 2 分钟",
      "自重深蹲 20 次 + 臀桥 15 次",
      "第一项逐级热身 3 组",
    ],
    exercises: [
      {
        id: "c1",
        name: "哈克深蹲",
        category: "compound",
        focus: "股四头主项",
        sets: 5,
        reps: "10",
        restSeconds: 150,
        cues: ["膝盖跟脚尖同向", "下蹲到底但不塌腰"],
        oneRepMaxRef: "hack_squat",
        progressionModel: "percentage",
        percentageOf1RM: 1,
        incrementKg: 5,
        substitutions: ["史密斯深蹲"],
        phaseAdaptive: true,
      },
      {
        id: "c2",
        name: "罗马尼亚硬拉",
        category: "compound",
        focus: "后链 / 臀腿",
        sets: 4,
        reps: "8-10",
        restSeconds: 120,
        cues: ["髋主导", "脊柱中立", "下放到腿后侧拉伸感明显"],
        oneRepMaxKg: 60,
        oneRepMaxRef: "rdl",
        progressionModel: "percentage",
        percentageOf1RM: 0.85,
        incrementKg: 2.5,
        substitutions: ["俯身腿弯举"],
      },
      {
        id: "c3",
        name: "反向山羊挺身",
        category: "core",
        focus: "核心刚性",
        sets: 3,
        reps: "12-15",
        restSeconds: 60,
        cues: ["向上伸展而非卷腹", "全程紧腹"],
        oneRepMaxKg: 10,
        progressionModel: "fixed",
        incrementKg: 0,
        substitutions: ["平板支撑"],
      },
      {
        id: "c4",
        name: "悬垂举腿",
        category: "core",
        focus: "腹部控制",
        sets: 3,
        reps: "10-12",
        restSeconds: 60,
        cues: ["控制下放", "避免身体晃动"],
        oneRepMaxKg: 10,
        progressionModel: "fixed",
        incrementKg: 0,
        substitutions: ["卷腹凳举腿"],
      },
      {
        id: "c5",
        name: "跪姿卷腹",
        category: "core",
        focus: "腹肌孤立",
        sets: 3,
        reps: "12-15",
        restSeconds: 45,
        cues: ["髋部为轴", "动作路径短而卷紧"],
        baseWeightKg: 15,
        oneRepMaxKg: 20,
        progressionModel: "fixed",
        incrementKg: 2.5,
        substitutions: ["绳索卷腹"],
      },
    ],
  },
];

export const defaultTemplates: WorkoutTemplate[] = applyCurrentTemplateLayout(defaultTemplateBlueprints);

export function buildDefaultPlanSetup(): PlanSetupInput {
  return regenerateLinearPlan({
    profile: defaultProfile,
    persona: defaultPersona,
    plan: defaultPlan,
    templates: defaultTemplates,
  });
}

export function buildEmptyDashboardSeed() {
  const setup = buildDefaultPlanSetup();
  return {
    profile: setup.profile,
    persona: setup.persona,
    plan: setup.plan,
    templates: setup.templates,
    nutritionDishes: [],
    recentBrief: null as DailyBrief | null,
    recentReports: [] as SessionReport[],
    proposals: [] as PlanAdjustmentProposal[],
    planSnapshots: [] as PlanSnapshot[],
    summaries: [] as { id: string; period: "daily" | "weekly"; date: string; summary: string; signals: string[]; createdAt: string }[],
    chatMessages: [],
  };
}

export function seedMemorySummary(summary: string, signals: string[]) {
  return {
    id: uid("summary"),
    period: "daily" as const,
    date: isoToday(),
    summary,
    signals,
    createdAt: new Date().toISOString(),
  };
}
